# Generated by Django 5.1 on 2024-09-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
