# Generated by Django 5.1 on 2024-09-15 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0003_rack_is_one_sided_rack_is_rotated_rack_side'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rack',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
