# Generated by Django 5.1 on 2024-09-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0004_strain_owner_alter_rack_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
